export const products = [
  {
    id: "p1",
    name: "Wireless Bluetooth Headphones",
    description: "High-quality wireless headphones with noise cancellation.",
    price: 99.99,
    currency: "USD",
    category: "Electronics",
    image: "./src/assets/images/headphone.jpg",
    rating: 4.5,
    quantity: 10,
    reviewsCount: 128,
    inStock: true,
  },
  {
    id: "p2",
    name: "Smart Fitness Watch",
    description: "Track your fitness, heart rate, and sleep activity.",
    price: 149.99,
    currency: "USD",
    category: "Wearables",
    image: "./src/assets/images/watch.jpg",
    rating: 4.2,
    quantity: 5,
    reviewsCount: 86,
    inStock: true,
  },
  {
    id: "p3",
    name: "Gaming Mechanical Keyboard",
    description: "RGB backlit mechanical keyboard with blue switches.",
    price: 79.99,
    currency: "USD",
    category: "Accessories",
    image: "./src/assets/images/keyboard.jpg",
    rating: 4.7,
    quantity: 8,
    reviewsCount: 203,
    inStock: false,
  },
  {
    id: "p4",
    name: "4K Ultra HD Monitor",
    description: "27-inch 4K monitor with ultra-thin bezels.",
    price: 329.99,
    currency: "USD",
    category: "Monitors",
    image: "./src/assets/images/monitor.jpg",
    rating: 4.6,
    quantity: 2,
    reviewsCount: 54,
    inStock: true,
  },
  {
    id: "p5",
    name: "Portable Power Bank",
    description: "20,000mAh fast-charging power bank with dual USB ports.",
    price: 39.99,
    currency: "USD",
    category: "Electronics",
    image: "./src/assets/images/powerbank.jpg",
    rating: 4.3,
    quantity: 12,
    reviewsCount: 311,
    inStock: true,
  },
];
